services:
  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=db
  adminer:
    image: adminer
    ports:
      - 8084:8080
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  mariadb_data:
    driver: local